name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   uses: actions/checkout@v2.3.5
            -   uses: actions/setup-dotnet@v1.8.2
                with:
                    dotnet-version: '5.0.x'
            -   name: Download protoc and protoc-doc-gen
                working-directory: build
                run: |
                    chmod +x download.sh
                    ./download.sh
            -   name: Create package
                run: dotnet pack -c Release src/Sitko.Grpc.Tools.Doc
            -   name: Add Github Actions logger
                run: dotnet add tests/Sitko.Grpc.Tools.Doc.Tests/Sitko.Grpc.Tools.Doc.Tests.csproj package GitHubActionsTestLogger
            -   name: Run tests
                run: dotnet test --logger GitHubActions tests/Sitko.Grpc.Tools.Doc.Tests/Sitko.Grpc.Tools.Doc.Tests.csproj

