name: Main

on:
    push:
        branches:
            - "*"
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   uses: actions/checkout@v2.3.5
            -   uses: actions/setup-dotnet@v2.1.1
                with:
                    dotnet-version: '5.0.x'
            -   name: Download protoc and protoc-doc-gen
                working-directory: build
                run: |
                    chmod +x download.sh
                    ./download.sh
            -   name: Create package
                run: dotnet pack -c Release src/Sitko.Grpc.Tools.Doc
            -   name: Add Github Actions logger
                run: dotnet add tests/Sitko.Grpc.Tools.Doc.Tests/Sitko.Grpc.Tools.Doc.Tests.csproj package GitHubActionsTestLogger
            -   name: Run tests
                run: dotnet test --logger GitHubActions tests/Sitko.Grpc.Tools.Doc.Tests/Sitko.Grpc.Tools.Doc.Tests.csproj
            -   name: Add Github Actions logger
                run: dotnet add tests/Sitko.Grpc.Tools.Doc.Tests/Sitko.Grpc.Tools.Doc.Tests.csproj package GitHubActionsTestLogger
            -   name: Run tests
                run: dotnet test --logger GitHubActions tests/Sitko.Grpc.Tools.Doc.Tests/Sitko.Grpc.Tools.Doc.Tests.csproj
    
    release:
        name: Release
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.5
                with:
                    fetch-depth: 0
                    persist-credentials: false
            -   name: Semantic Release
                uses: sitkoru/semantic-release-action@v1
                env:
                    GH_TOKEN: ${{ secrets.BOT_TOKEN }}
                    GIT_AUTHOR_NAME: ${{ secrets.BOT_NAME }}
                    GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
                    GIT_COMMITTER_NAME: ${{ secrets.BOT_NAME }}
                    GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
